CREATE TABLE TBCOMBUSTIVEL(
    ID_COMBUSTIVEL INT,
    DESCRICAO VARCHAR(50) NOT NULL,
    VALOR NUMERIC(12,6) NOT NULL,
    IMPOSTO NUMERIC(12,6) NOT NULL,    
    
    PRIMARY KEY(ID_COMBUSTIVEL)
);

CREATE TABLE TBTANQUE(
    ID_TANQUE INT,
    ID_COMBUSTIVEL INT REFERENCES TBCOMBUSTIVEL(ID_COMBUSTIVEL),
    
    PRIMARY KEY(ID_TANQUE)
);

CREATE TABLE TBBOMBA(
    ID_BOMBA INT,
    ID_TANQUE INT REFERENCES TBTANQUE(ID_TANQUE),
    
    PRIMARY KEY(ID_BOMBA)
);

CREATE TABLE TBABASTECIMENTO(
    ID_ABASTECIMENTO INT,
    ID_BOMBA INT REFERENCES TBBOMBA(ID_BOMBA),
    DATA DATE NOT NULL,
    QUANTIDADE NUMERIC(12,6) NOT NULL,
    VALOR NUMERIC(12,6) NOT NULL,
    VALOR_IMPOSTO NUMERIC(12,6) NOT NULL,   
    
    PRIMARY KEY(ID_ABASTECIMENTO)
);