select * from (
select 
    A.DATA,
    A.ID_BOMBA,
    B.ID_TANQUE,
    C.DESCRICAO,
    SUM(A.QUANTIDADE) AS QUANTIDADE,
    SUM(A.VALOR) AS VALOR,
    SUM(A.VALOR_IMPOSTO) AS VALOR_IMPOSTO    
 from TBABASTECIMENTO A
 join TBBOMBA B ON
 (B.ID_BOMBA = A.ID_BOMBA)
join TBTANQUE T ON
 (T.ID_TANQUE = B.ID_TANQUE) 
join TBCOMBUSTIVEL C ON
 (C.ID_COMBUSTIVEL = T.ID_COMBUSTIVEL)  
 GROUP BY
    A.ID_BOMBA,
    A.DATA,
    B.ID_TANQUE,
    C.DESCRICAO    
)